### ISSUE TITLE
dmg for arm macs won't open

### ISSUE THREAD

**Issue by jcvernaleo** [Lumerin-protocol/WalletDesktop#113]
On an M2 (arm) based mac with latest os, installed `dev-lumerin_v1.0.49_arm.dmg`.  When I try to start the app, a popup that says:
`"Lumerin Wallet.app" is damaged and can't be opened.  You should move it to the trash.`

**Comment by jcvernaleo** [comment]
The non-arm version does open on the same arm mac.

**Comment by LumerinIO** [comment]
Exalate commented: GitHub source link is https://github.com/Lumerin-protocol/WalletDesktop/issues/113

**Comment by LumerinIO** [comment]
Alan Sorber commented: John, this is a known issue until we get our certificates and signature injected…for the time being this is the workaround from the CLI: 
{{xattr -c /Applications/Lumerin\ Wallet.app}} 

this will allow non signed code to run but will not allow it to automatically change system functionality (so you’ll get password prompts from proxy-router when it starts up)

**Comment by jcvernaleo** [comment]
Interesting that the behavior is different for the arm and the amd64 dmg but it does work with that extra command.

**Comment by LumerinIO** [comment]
Alan Sorber commented: Yes, it’s because of Rosetta translator running on ARM for the intel package doesn’t allow base system access like the native one does.  So finding the Intel version on ARM and right clicking opens it right up (manual approval that it’s not a security risk).  The native version isn’t as forgiving to run outside of or without sandboxing…so clearing the extended attributes (for now) works.

**Comment by jcvernaleo** [comment]
At least they did this cleaner than the ppc to intel transition :)

**Comment by LumerinIO** [comment]
Alan Sorber commented: Truly!
